Add nix-unstable and `deploy` to buildkite runtimePackages
serokell/aquarius-infra pull request #15
Opened 2020-12-15 01:16 UTC by notgne2

2020-12-16 21:21 UTC, mkaito requested changes

2020-12-16 21:21 UTC, mkaito commented on common/buildkite.nix
> +            ${inputs.nix-master.packages.${pkgs.system}.nix}/bin/nix --experimental-features 'nix-command flakes' $@
The `--experimental-features` flag is reserved for `trusted-users`. You'll need to enable it at the system level. Also, are you sure you don't want to quote `$@`?

2020-12-17 23:21 UTC, notgne2 commented
Not sure if the extraOptions stuff was put in a good place since mkBuildkite seems to be generally for per-instance stuff

2020-12-18 17:14 UTC, mkaito commented
That should probably be outside the function, yes.

2020-12-18 17:33 UTC, notgne2 commented
@mkaito any suggestion for where?

2020-12-24 01:11 UTC, mkaito commented
Given that those two particular features are used everywhere, maybe serokell.nix

2021-01-09 02:20 UTC, notgne2 commented
@mkaito review pls

2021-01-09 08:24 UTC, balsoft commented on common/buildkite.nix
> +          '')
Is there any reason to not just add `inputs.nix-master.packages.${pkgs.system}.nix` to the list instead of a custom script?

2021-01-09 08:25 UTC, balsoft commented on common/buildkite.nix
> +          inputs.deploy-rs.defaultPackage.${pkgs.system}
I think given `deploy-rs.lib` must be used in flakes, it's reasonable to always use the version that's pinned in that particular flake, especially until we have established semver.

2021-01-10 21:09 UTC, notgne2 commented on common/buildkite.nix
> +          '')
I don't want unstable Nix to be the default, this way it is called via `nix-unstable`, not `nix`

2021-01-10 21:10 UTC, notgne2 commented on common/buildkite.nix
> +          inputs.deploy-rs.defaultPackage.${pkgs.system}
That's what we'll keep to doing after this PR I think, but this prepares us for the future where there won't be a need anymore

2021-01-28 08:14 UTC, zhenyavinogradov commented
In my opinion, it's better to pin concrete versions of deploy-rs and nix-unstable in the repos that use them, instead of having them globally available in CI. It makes it harder to update them, but having unpinned dependencies in CI usually causes more troubles.

2021-01-28 22:03 UTC, notgne2 commented
To provide a bit more justification on why I want this to pass though:

The way we pin deploy-rs and unstable Nix, and utilize them within the build scripts is unnecessarily complex, making OPS-958 more complicated, and Nix and other utilities are also used in a non-fixed manner regardless of this PR (as in, everything else in `runtimePackages`). They both also will have frequent updates which are very often relevant to our own deployments, so like you said, updating in each individual project will be more inconvenient.

It also doesn't make us any more error-prone given that it is pinned in this PR too, just in a centralized location.

I don't plan to start using deploy-rs from the environment right away either, just the `nix-unstable` binary.

2021-02-01 16:30 UTC, mkaito commented
After thinking about it for a little bit, I agree with Mika. Anything that could potentially break build and/or deployment of a given repository should be pinned in that repository, and only updated after manual review and verification.

However, deploy-rs and unstable Nix aren't really dependencies in that sense. We just need to have a version of them available at build time that we know works, and which can (and probably should) be the same for all of its dependents.

On the other hand, removing these from the Flake of each repository means that the `devShell`, which should contain all necessary tools and dependencies to work on a given project, will no longer do its job; which is something I dislike.

2021-02-03 07:56 UTC, zhenyavinogradov commented
We would want to have deploy-rs pinned for the same reason we pin everything else. We don't want the pipeline fail unexpectedly, because a tool it was using was repinned in the builder config some time ago, and the new version is incompatible with the repo. If we have it pinned in the repo, we can always postpone updating it until we fix problems related to the update, and we'll also be able to know which update caused issues. I've discussed it with @notgne2 yesterday, and he agreed with that too.

But for nix-unstable I guess it's fine to have it in the environment together with the stable nix, because running stable nix to get unstable nix seems awkward, having global nix-unstable allows us to use it directly.

2021-02-03 07:58 UTC, zhenyavinogradov approved these changes

2021-02-10 03:39 UTC, merged